version: '3'

services :
    db:
        container_name: db
        build: ./db
        ports: 
            - "5432:5432"
        restart: "always"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
        networks: 
            - backend
        volumes:
            - db:/var/lib/postgresql/data
    
    nginx1:
        container_name: nginx1
        build: ./nginx1
        ports: 
            - "8081:80"
        restart: "always"
        networks:
            - backend
            - frontend
        volumes:
            - nginx1:/usr/share/nginx/html
    
    nginx2:
        container_name: nginx2
        build: ./nginx2
        ports: 
            - "8082:80"
        restart: "always"
        networks:
            - backend
            - frontend
        volumes:    
            - nginx2:/usr/share/nginx/html
    
    nginx3:
        container_name: nginx3
        build: ./nginx3
        ports: 
            - "8083:80"
        restart: "always"
        networks:
            - backend
            - frontend
        volumes:
            - nginx3:/usr/share/nginx/html
    
    loadbalancer:
        container_name: loadbalancer
        build: ./loadbalancer
        ports:
            - "8080:80"
        networks:
            - frontend
        restart: "always"
        volumes:
            - loadbalancer:/etc/nginx/:ro

networks:
    backend:
        internal: true
    frontend:
        internal: false


volumes:
    db:
    loadbalancer:
    nginx1:
    nginx2:
    nginx3: